[project]
name = "mf6xtd"
version = "1.0.0"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]

[system-requirements]
linux = "4.4.0"

[tasks]
install-flopy = "pip install https://github.com/modflowpy/flopy/zipball/develop"

initialize = "export PKG_CONFIG_PATH= && export PATH="
update-pc-files = { cmd = "python update_pc_files.py", cwd = "installation" }
clone-modflow = "rm -rf modflow6/ && git clone https://github.com/MODFLOW-USGS/modflow6.git"
update-flopy = { cmd = "python update_flopy.py", cwd = "modflow6/autotest" }
setup-modflow = { cmd = "rm -rf builddir && meson setup builddir -Ddebug=false -Dextended=true --prefix=$PIXI_PROJECT_ROOT/.pixi/envs/default/", cwd = "modflow6" }
install-modflow = { cmd = "meson install -C builddir", cwd = "modflow6" }
test-modflow = { cmd = "meson test --verbose --no-rebuild -C builddir", cwd = "modflow6" }
obtain-modflow = { depends_on = [
  "initialize",
  "update-pc-files",
  "clone-modflow",
  "update-flopy",
  "setup-modflow",
  "install-modflow",
  "test-modflow",
] }

test-installation = { cmd = "python test_installation.py", cwd = "installation" }

install = { depends_on = [
  "install-flopy",
  "obtain-modflow",
  "test-installation",
] }
jupyter = "export PATH=.pixi/envs/default/bin:.pixi/envs/default/lib:$PATH && export PKG_CONFIG_PATH= && jupyter lab"

[target.win-64.tasks]
clone-modflow-win = { cmd = "rm -rf modflow6; git clone https://github.com/MODFLOW-USGS/modflow6.git" }
update-flopy-win = { cmd = "python update_flopy.py", cwd = "modflow6/autotest" }
download-modflow-win = { cmd = "python -c 'from urllib.request import urlretrieve; urlretrieve(\"https://github.com/MODFLOW-USGS/modflow6-nightly-build/releases/download/20241107/win64ext.zip\", \"win64ext.zip\")'" , outputs=["win64ext.zip"]}
unzip-modflow-win = { cmd = "python -c 'import shutil; shutil.unpack_archive(\"win64ext.zip\", \"win64ext\")'" }
install-modflow-win = {cmd = "python -c 'import shutil; import glob; shutil.copytree(glob.glob(\"win64ext/**/bin\")[0], \".pixi/envs/default/bin\", dirs_exist_ok=True)'" }
obtain-modflow = { depends_on = [
  "clone-modflow-win",
  "update-flopy-win",
  "download-modflow-win",
  "unzip-modflow-win",
  "install-modflow-win",
] }

[dependencies]
# required
python = "<=3.12"
numpy = ">=1.15.0"
matplotlib = ">=1.4.0"
jupyterlab = "*"
pip = "*"

# development (largely redundant for win64)
pkg-config = "*"
gfortran = "*"
clang = "*"
meson = ">=1.1.0"
ninja = "*"
pytest = "*"
modflow-devtools = "*"

# flopy
python-dateutil = ">=2.4.0"
affine = "*"
scipy = "*"
pandas = ">=2.2.0"
pyshp = "*"
rasterio = "*"
fiona = "*"
descartes = "*"
pyproj = "*"
shapely = ">=1.8"
geos = "*"
geojson = "*"
vtk = "*"
rasterstats = "*"
pyvista = "*"
imageio = "*"
pymetis = "*"
netcdf4 = "*"
xarray = "*"
xmipy = "*"
modflowapi = "*"

# notebooks
xugrid = "*"
ipywidgets = "*"

[target.linux-64.dependencies]
openmpi = "*"
libnetcdf = "*"
netcdf-fortran = "*"
petsc = "*"

[target.linux-aarch64.dependencies]
openmpi = "*"
libnetcdf = "*"
netcdf-fortran = "*"
petsc = "*"

[target.osx-64.dependencies]
openmpi = "*"
libnetcdf = "*"
netcdf-fortran = "*"
petsc = "*"

[target.osx-arm64.dependencies]
openmpi = "*"
libnetcdf = "*"
netcdf-fortran = "*"
petsc = "*"